setwd("C:/Users/Dr.Sobhan/Desktop/Dec2016/Data sets/5-Logistic Regression/")
setwd("C:/data/E/ashok2017/Dec2016/Data sets/5-Logistic Regression")
liver= read.table("liver.csv",header=T)
summary(liver)
liver= read.csv("liver.csv",header=T)
summary(liver)
attach(liver)
plot(Age,Gender,Total_Bilirubin,Direct_Bilirubin,Alkaline_Phosphotase,Alamine_Aminotransferase, Aspartate_Aminotransferase,Total_Protiens,Albumin  col=outcome+1)
plot(Age,Gender,Total_Bilirubin,Direct_Bilirubin,Alkaline_Phosphotase,Alamine_Aminotransferase, Aspartate_Aminotransferase,Total_Protiens,Albumin,col=outcome+1)
plot(Age,Gender,Total_Bilirubin,Direct_Bilirubin,Alkaline_Phosphotase,Alamine_Aminotransferase, Aspartate_Aminotransferase,Total_Protiens,Albumin,col=outcome)
plot(Age,Gender,Total_Bilirubin,Direct_Bilirubin,Alkaline_Phosphotase,Alamine_Aminotransferase, Aspartate_Aminotransferase,Total_Protiens,Albumin,col=outcome+1)
health= read.csv("health.csv")
attach(health)
plot(weight,BP,col=Suffered.Heart.storke+1)
plot(Total_Bilirubin,Direct_Bilirubin,col=outcome+1)
model = glm(outcome~Age+Gender+Total_Bilirubin+Direct_Bilirubin+Alkaline_Phosphotase+Alamine_Aminotransferase+Aspartate_Aminotransferase+Total_Protiens+Albumin, family=binomial,data=liver)
summary(model)
model = glm(outcome~., family=binomial,data=liver)
model1 = glm(outcome~., family=binomial,data=liver)
summary(model1)
model2 = glm(outcome~1, family=binomial,data=liver)
summary(model2)
plot(model1)
plot(model2)

step(model2,scope = list(upper=model),direction="both",test="Chisq",data=liver)
step(model2,scope = list(upper=model1),direction="both",test="Chisq",data=liver)
step(model1,scope = list(upper=model2),direction="both",test="Chisq",data=liver)
step(model2,scope = list(upper=model1),direction="forward",test="Chisq",data=liver)
step(model2,scope = list(upper=model1),direction="backward",test="Chisq",data=liver)
model.null = glm(Status ~ 1,data=liver,family = binomial(link="logit"))
model.null = glm(outcome ~ 1,data=liver,family = binomial(link="logit"))
summary(model.null)
model.full = glm(outcome ~ 1,data=liver,family = binomial(link="logit"))
summary(model.full)
model.full = glm(outcome ~ .,data=liver,family = binomial(link="logit"))
summary(model.full)
finalmodel1 =glm((formula = outcome ~ Direct_Bilirubin+ Total_Bilirubin+ Aspartate_Aminotransferase+ Alamine_Aminotransferase+ Alkaline_Phosphotase, family = binomial, data = liver)
finalmodel1 =glm((formula = outcome ~ Direct_Bilirubin + Total_Bilirubin + Aspartate_Aminotransferase + Alamine_Aminotransferase + Alkaline_Phosphotase, family = binomial, data = liver)
finalmodel1 =glm((outcome ~ Direct_Bilirubin + Total_Bilirubin + Aspartate_Aminotransferase + Alamine_Aminotransferase + Alkaline_Phosphotase, family = binomial, data = liver)
finalmodel1 =glm((outcome ~ Direct_Bilirubin+Total_Bilirubin+Aspartate_Aminotransferase +Alamine_Aminotransferase +Alkaline_Phosphotase, family = binomial,data = liver)
finalmodel1 =glm((outcome ~ Direct_Bilirubin+Total_Bilirubin+Aspartate_Aminotransferase +Alamine_Aminotransferase +Alkaline_Phosphotase,family = binomial,data = liver)
                                                                                     finalmodel1 =glm(outcome ~ Direct_Bilirubin+Total_Bilirubin+Aspartate_Aminotransferase +Alamine_Aminotransferase +Alkaline_Phosphotase,family = binomial,data = liver)
                                                                                     summary(finalmodel1)
                                                                                     pchisq(null.deviance - residual deviance,  df.null - df.residual,  lower.tail = FALSE)
                                                                                     pchisq(null.deviance - residual deviance,  df.null - df.residual,  lower.tail = FALSE)
                                                                                     pchisq(null deviance-residual deviance,df.null-df.residual, lower.tail= FALSE)
                                                                                     pchisq(null deviance -residual deviance ,df.null-df.residual, lower.tail= FALSE)
                                                                                     pchisq(null.deviance - residual deviance,  df.null - df.residual,  lower.tail = FALSE)
                                                                                     n=nrow(liver)
                                                                                     n
                                                                                     n1=floor(n*(0.7))
                                                                                     n1
                                                                                     n2=n-n1
                                                                                     n2
                                                                                     train=sample(1:n,n1)
                                                                                     model = glm(outcome~Direct_Bilirubin+Alamine_Aminotransferase+Total_Protiens+Albumin, family=binomial,data=liver[train,])
                                                                                     summary(model)
                                                                                     pchisq(null.deviance - residual deviance,  df.null - df.residual,  lower.tail = FALSE)
                                                                                     pchisq(null.deviance - residual deviance, df.null - df.residual, lower.tail = FALSE)
                                                                                     ptrain <- predict(model,newdata=liver[train,],type="outcome")
                                                                                     ptrain <- predict(model,newdata=liver[train,],type = outcome)
                                                                                     ptrain <- predict(model,data=liver[train,],type = outcome)
                                                                                     
                                                                                     